### ISSUE TITLE
Weird Code & Test glitch 

### ISSUE THREAD

**Issue by radames** [stlim0730/glide#60]
Can't navigate over the tabs after the glitch.

Is there any other workflow to help you debug what's happening?

<img width="1678" alt="screen shot 2018-04-10 at 17 59 30" src="https://user-images.githubusercontent.com/102277/38590916-014c064c-3ce9-11e8-9444-2d06045ed98f.png">

**Comment by radames** [comment]
Another update a short gif with the clicks problem, it's reproducible just clicking fast between the files tabs
![error](https://user-images.githubusercontent.com/102277/38648790-f3d63446-3da7-11e8-8487-bdc5f8f2b00b.gif)

**Comment by stlim0730** [comment]
I think this is because of React's internal overhead in updating a component's state while bootstrap is rendering dynamic components in parallel.

GLIDE is not using [react-bootstrap](https://github.com/react-bootstrap/react-bootstrap) package, but the similar issue has been reported in their issues [Tab panel disappears when switching tabs quickly](https://github.com/react-bootstrap/react-bootstrap/issues/1936).

The second example of the fast click problem in branch phase looks less crucial than the problem in coding phase.

Two possible quick measures that are worth a try:

1. Disable animation of tab appearance, which might help immediate rendering of the tabbed pane.
2. Disable mouse cursor (e.g., hourglass) for 2 seconds right after those clicks.

The ultimate solution will be to fine tune the order of updating and rendering, but I'm not sure how to do this for now. Thanks for your report, @radames!

**Comment by stlim0730** [comment]
Fixed!

The problem was that the tab behavior was implemented in two ways: React-controlled and uncontrolled (using Bootstrap's global rules).

Now tab works in the React-controlled way.
